import React, { useState } from 'react';
import { Compass, Play, Sparkles, Heart, Search, Copy, Check, Filter } from 'lucide-react';
import { VideoItem } from '../types';
import { EXPLORE_CATEGORIES } from '../data/mockVideos';

interface ExploreGalleryProps {
  videos: VideoItem[];
  onSelectVideo: (video: VideoItem) => void;
  onUsePrompt: (prompt: string, style: VideoItem['style'], camera: VideoItem['cameraControl']) => void;
  showToast: (type: 'success' | 'error' | 'info' | 'warning', title: string, message: string) => void;
}

export const ExploreGallery: React.FC<ExploreGalleryProps> = ({
  videos,
  onSelectVideo,
  onUsePrompt,
  showToast,
}) => {
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [hoveredVideoId, setHoveredVideoId] = useState<string | null>(null);
  const [likedMap, setLikedMap] = useState<Record<string, boolean>>({});
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleToggleLike = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const nextState = !likedMap[id];
    setLikedMap((prev) => ({ ...prev, [id]: nextState }));
    if (nextState) {
      showToast('success', 'Liked', 'Added to your liked community videos.');
    }
  };

  const handleCopyPrompt = (video: VideoItem, e: React.MouseEvent) => {
    e.stopPropagation();
    if (navigator.clipboard) {
      navigator.clipboard.writeText(video.prompt);
      setCopiedId(video.id);
      setTimeout(() => setCopiedId(null), 2000);
      showToast('info', 'Prompt Copied', 'Prompt copied to clipboard.');
    }
  };

  const filteredVideos = videos.filter((video) => {
    const matchesCategory =
      selectedCategory === 'All' ||
      video.category.toLowerCase() === selectedCategory.toLowerCase() ||
      video.style.toLowerCase().includes(selectedCategory.toLowerCase()) ||
      video.tags.some((t) => t.toLowerCase() === selectedCategory.toLowerCase());

    const matchesSearch =
      searchQuery === '' ||
      video.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      video.prompt.toLowerCase().includes(searchQuery.toLowerCase()) ||
      video.authorName.toLowerCase().includes(searchQuery.toLowerCase());

    return matchesCategory && matchesSearch;
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-2">
          <span className="p-1.5 rounded-lg bg-cyan-500/10 text-cyan-400">
            <Compass className="w-5 h-5" />
          </span>
          <h1 className="text-3xl sm:text-4xl font-display font-extrabold text-white tracking-tight">
            Explore Community Generations
          </h1>
        </div>
        <p className="text-sm sm:text-base text-slate-400 max-w-2xl">
          Discover cinematic masterpiece videos generated by the VisionFlow AI community. Copy prompts or remix them directly in the studio.
        </p>
      </div>

      {/* Search Bar & Category Filter Bar */}
      <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4 mb-8">
        {/* Search */}
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input
            id="explore-search-input"
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search prompts, styles, creators..."
            className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/50"
          />
        </div>

        {/* Category Filter Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-2 md:pb-0 scrollbar-none">
          {EXPLORE_CATEGORIES.map((category) => {
            const isSelected = selectedCategory === category;
            return (
              <button
                key={category}
                id={`explore-cat-${category.toLowerCase().replace(/\s+/g, '-')}`}
                onClick={() => setSelectedCategory(category)}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                  isSelected
                    ? 'bg-gradient-to-r from-cyan-500 to-indigo-600 text-white shadow-md shadow-cyan-500/20'
                    : 'bg-slate-900/80 hover:bg-slate-800 border border-slate-800 text-slate-300 hover:text-white'
                }`}
              >
                {category}
              </button>
            );
          })}
        </div>
      </div>

      {/* Video Grid */}
      {filteredVideos.length === 0 ? (
        <div className="py-20 text-center glass-panel rounded-2xl border-slate-800">
          <Filter className="w-10 h-10 text-slate-600 mx-auto mb-3" />
          <p className="text-base font-bold text-white">No videos matched your filter</p>
          <p className="text-xs text-slate-400 mt-1">Try searching for a different keyword or selecting 'All'.</p>
          <button
            onClick={() => {
              setSelectedCategory('All');
              setSearchQuery('');
            }}
            className="mt-4 px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-cyan-300"
          >
            Reset Filters
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredVideos.map((video) => {
            const isHovered = hoveredVideoId === video.id;
            const isLiked = likedMap[video.id];
            const likeCount = video.likes + (isLiked ? 1 : 0);

            return (
              <div
                key={video.id}
                id={`explore-card-${video.id}`}
                onMouseEnter={() => setHoveredVideoId(video.id)}
                onMouseLeave={() => setHoveredVideoId(null)}
                className="group relative rounded-2xl overflow-hidden glass-panel-interactive border-slate-800/80 flex flex-col cursor-pointer"
                onClick={() => onSelectVideo(video)}
              >
                {/* Media Thumbnail / Video Preview */}
                <div className="relative aspect-video w-full overflow-hidden bg-slate-950">
                  {isHovered ? (
                    <video
                      src={video.videoUrl}
                      poster={video.thumbnailUrl}
                      autoPlay
                      muted
                      loop
                      playsInline
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                  ) : (
                    <img
                      src={video.thumbnailUrl}
                      alt={video.title}
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                      loading="lazy"
                    />
                  )}

                  {/* Gradient overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/30 pointer-events-none" />

                  {/* Play Button Icon Overlay */}
                  <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                    <div className="w-12 h-12 rounded-full bg-cyan-500/30 backdrop-blur-md border border-cyan-400/40 flex items-center justify-center text-white shadow-xl opacity-0 group-hover:opacity-100 transition-opacity transform group-hover:scale-110">
                      <Play className="w-5 h-5 fill-white ml-0.5" />
                    </div>
                  </div>

                  {/* Top Badges */}
                  <div className="absolute top-3 left-3 right-3 flex items-center justify-between z-10 pointer-events-none">
                    <span className="px-2.5 py-1 rounded-full bg-black/60 backdrop-blur-md text-[10px] font-bold uppercase tracking-wider text-cyan-300 border border-white/10">
                      {video.style}
                    </span>
                    <span className="px-2 py-0.5 rounded-full bg-black/60 backdrop-blur-md text-[10px] font-mono text-slate-300 border border-white/10">
                      {video.duration} • {video.quality}
                    </span>
                  </div>

                  {/* Camera Shot Badge bottom left */}
                  <div className="absolute bottom-2.5 left-3 z-10 pointer-events-none">
                    <span className="text-[10px] font-mono text-slate-300 capitalize bg-black/50 px-2 py-0.5 rounded-md backdrop-blur-sm">
                      {video.cameraControl.replace('-', ' ')}
                    </span>
                  </div>
                </div>

                {/* Card Content Info */}
                <div className="p-4 flex-1 flex flex-col justify-between space-y-3">
                  <div>
                    <h3 className="text-sm font-bold text-white group-hover:text-cyan-300 transition-colors line-clamp-1">
                      {video.title}
                    </h3>
                    <p className="text-xs text-slate-300/80 line-clamp-2 mt-1 italic">
                      “{video.prompt}”
                    </p>
                  </div>

                  {/* Creator and Actions Footer */}
                  <div className="pt-2 border-t border-slate-800/80 flex items-center justify-between text-xs">
                    {/* Author */}
                    <div className="flex items-center gap-2">
                      <img
                        src={video.authorAvatar}
                        alt={video.authorName}
                        className="w-5 h-5 rounded-full object-cover ring-1 ring-cyan-500/40"
                      />
                      <span className="text-slate-300 font-medium truncate max-w-[100px]">
                        {video.authorName}
                      </span>
                    </div>

                    {/* Likes & Remix Buttons */}
                    <div className="flex items-center gap-1.5" onClick={(e) => e.stopPropagation()}>
                      <button
                        id={`copy-prompt-btn-${video.id}`}
                        onClick={(e) => handleCopyPrompt(video, e)}
                        className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                        title="Copy prompt"
                      >
                        {copiedId === video.id ? (
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                        ) : (
                          <Copy className="w-3.5 h-3.5" />
                        )}
                      </button>

                      <button
                        id={`like-video-btn-${video.id}`}
                        onClick={(e) => handleToggleLike(video.id, e)}
                        className={`flex items-center gap-1 px-2 py-1 rounded-lg transition-colors ${
                          isLiked
                            ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                            : 'hover:bg-slate-800 text-slate-400 hover:text-white'
                        }`}
                        title="Like video"
                      >
                        <Heart className={`w-3.5 h-3.5 ${isLiked ? 'fill-rose-400' : ''}`} />
                        <span className="text-[11px] font-mono">{likeCount}</span>
                      </button>

                      <button
                        id={`remix-btn-${video.id}`}
                        onClick={(e) => {
                          e.stopPropagation();
                          onUsePrompt(video.prompt, video.style, video.cameraControl);
                        }}
                        className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-cyan-500/15 hover:bg-cyan-500/25 text-cyan-300 border border-cyan-500/30 text-[11px] font-semibold transition-all hover:scale-105"
                        title="Open in Generator"
                      >
                        <Sparkles className="w-3 h-3" />
                        <span>Remix</span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
